package com.example.managedatatypes;

import android.provider.BaseColumns;

public final class SQLiteContract {

    private SQLiteContract(){

    }

    // CONTAINER FOR DIFFERENT CONSTANTS FOR SQLITE IF WE NEED TO CHANGE A COLUMN NAME, NOTHING ELSE
    // WE CREATE AN INNER CLASS FOR EACH TABLE IN OUR DATABASE
    // HERE WE CREATE THE CONSTANTS THAT WILL CONTAIN THE SAME INFORMATION THAT WE HAVE IN QUESTIONS JAVA CLASS
    // ALSO THE NAME OF THE TABLE
    // THE ARE STRING VALUES AND ARE PUBLIC BECAUSE TO ACCESS OUTSIDE THIS CLASS
    // THEY ARE STATIC BECAUSE YOU WANT TO ACCESS THEM WITHOUT NEEDING AN INSTANCE OF THIS QUESTION TABLE
    // THEY ARE FINAL BECAUSE WE DON'T WANT TO CHANGE THEM
    // WE MAKE MoodContract FINAL SO THAT WE CAN'T SUBCLASS IT AND ADDITIONALLY WE WILL ALSO CREATE A PRIVATE CONSTRUCTOR
    // THIS WAY WE CAN'T CREATE AN OBJECT OF THIS MoodContract BY ACCIDENT
    // WE CANT SUBCLASS IT AND WE CAN'T CREATE AN OBJECT IT
    // THIS IS TO MAKE SURE WE ONLY USE THIS CLASS AS A CONTAINER FOR THESE CONSTANTS AND NOTHING ELSE
    // THIS IS BETTER WHEN WORKING WITH TEAMS AS GOOD PRACTICE

    public static class SaveUsersTable implements BaseColumns {

        // BASE COLUMNS IS AN INTERFACE AND WHEN WE CLICK ON IT AND PRESS CTRL + B WE GET INTO ITS DECLARATION
        // ALL THIS INTERFACE DOES IS PROVIDE TWO MORE CONSTANTS - "ID" AND "COUNT" WE WILL ONLY USE "ID"
        // WE WILL USE THE "ID" CONSTANT TO CREATE ANOTHER COLUMN IN OUR DATABASE TO STORE THE ID
        // THE ID IS SIMPLY A NUMBER THAT WILL AUTOMATICALLY INCREMENT WITH EACH NEW ENTRY IN THE QUIZ TABLE
        // WE CAN USE THIS ID TO UNIQUELY IDENTIFY EACH ENTRY
        // TO DELETE OR EDIT ENTRIES WE NEED THIS TO IDENTIFY THEM
        // WE COULD ALSO MAKE THE ID COLUMN BELOW
        // THE CURSOR ADAPTER NEEDS THIS EXACT NAMING CONVENTION "_id";

        public static final String TABLE_USERS = "user_details";
        public static final String COLUMN_DATE = "Date";
        public static final String COLUMN_NAME = "Name";
        public static final String COLUMN_EMAI = "Email";
        public static final String COLUMN_PASS = "Password";
    }
}

